services:
  falco:
    image: falcosecurity/falco:latest
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
    command: [ "/usr/bin/falco", "-K", "/host", "-pk" ]
    privileged: true